### ISSUE TITLE
RobiniaDocs API Explorer

### ISSUE THREAD

**Issue by NeuroXiq** [Marvin-Brouwer/FluentSerializer#353]
Maybe You will be interested in hosting API Explorer online:

[![Static Badge](https://img.shields.io/badge/API%20Documentation-RobiniaDocs-43bc00?logo=readme&logoColor=white)](https://www.robiniadocs.com/d/fluentseri/api/FluentSerializer.Json.Converting.Converters.html)

https://www.robiniadocs.com/d/fluentseri/api/FluentSerializer.Json.Converting.Converters.html

**Comment by Marvin-Brouwer** [comment]
Hi, these kinds of tools are very useful for proprietary SDKs and APIs.
However, for this library we've chosen to keep the documentation close to the code by providing readme's and markdown files in the repo itself 
We appreciate the suggestion. But, at this point in time we have no intention to host any kind of documentation elsewhere.

Thanks for suggesting though.
